### ISSUE TITLE
.gitignore / .remote files

### ISSUE THREAD

**Issue by ghost** [sybethiesant/pidoors#1]
Hey, I was checking out your repo. 

Love the project and Wana make use of it, but I also noticed your .remote files in the [.gitignore](https://github.com/sybethiesant/pidoors/blob/main/.gitignore)  file but they are still visible in te folders [/pidoorserv](https://github.com/sybethiesant/pidoors/tree/main/pidoorserv)  and [/pidoors](https://github.com/sybethiesant/pidoors/tree/main/pidoors)  with possible sensitive data. (Not gonna share a screenshot of it so the data inside is not visible here 😬😉)

Just wanted to let you know @sybethiesant 

![Screenshot_20210914-133837](https://user-images.githubusercontent.com/77323117/133250961-cad7caeb-0db0-4ca0-b1b8-5157908c89ab.jpg)
![Screenshot_20210914-133827](https://user-images.githubusercontent.com/77323117/133250965-371a08b8-cb6c-4867-95ef-dc56f4e57540.jpg)

**Comment by sybethiesant** [comment]
I appreciate it and resolved that issue. 

Ive been so busy with work I haven't been able to move forward with alot of the finalization of the gui and such for this. however its been implemented at my work for our parts container and a minor security gate. It's been working great in those locations so far. If you make any good changes or clean up some of my dirty code let me know! have a good one!
